name: Deploy

on: [workflow_dispatch]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend
    env:
      CI: false
      SERVER_URL: http://mateuszkifner.ct8.pl

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Add .htaccess
        run: |
          cat > build/.htaccess <<- EOM
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /subdirectory
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-l
            RewriteRule . /index.html [L]
          </IfModule>
          EOM
          cat build/.htaccess
        shell: bash
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "frontend/build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
